---
title: "Implementation"
author: "Simon Adamov"
date: "August 12, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      error = FALSE, 
                      warning = FALSE, 
                      message = FALSE,
                      fig.retina =3,
                      fig.width = 10,
                      fig.height = 7,
                      out.width = "100%",
                      out.height = "100%")

library(mchdwh)
library(dplyr)
library(lubridate)
library(purrr)
library(ggthemr)
# devtools::install_github('cttobin/ggthemr')
ggthemr("fresh")
```

# Data Import

## Hirst Trap Measurements 2020 - All Stations

The data is obtained from the DWH for the current pollen season (2020). 

```{r}

# The following types are being measured:
# Erle - Alder - Aulne - Alnus
# Birke - Birch - Bouleau - Betula
# Gräser - Grasses - Graminées - Poaceae
# Ambrosia - Ragweed - Ambroisie - Ambrosia

species_all <- tibble(
  taxon = c(
    "Castanea",
    "Alnus",
    "Ulmus",
    "Cupressus",
    "Fraxinus",
    "Fagus",
    "Juglans",
    "Plantago",
    "Corylus",
    "Pinus",
    "Quercus",
    "Rumex",
    "Platanus",
    "Populus",
    "Poaceae",
    "Salix",
    "Betula",
    "Carpinus",
    "Urtica",
    "Taxus",
    "Picea",
    "Ambrosia"
  ),
  tag = c(
    "kacasth0",
    "kaalnuh0",
    "kaulmuh0",
    "kacuprh0",
    "kafraxh0",
    "kafaguh0",
    "kajuglh0",
    "khplanh0",
    "kacoryh0",
    "kapinuh0",
    "kaquerh0",
    "khrumeh0",
    "kaplath0",
    "kapopuh0",
    "khpoach0",
    "kasalih0",
    "kabetuh0",
    "kacarph0",
    "khurtih0",
    "kataxuh0",
    "kapiceh0",
    "khambrh0"
  )
)

species <- species_all %>%
  filter(taxon %in% c("Alnus", "Ambrosia", "Betula", "Poaceae"))

stations <-
  tibble(
    tag = c(
      "PDS",
      "PBU",
      "PMU",
      "PBS",
      "PZH",
      "PLZ",
      "PBE",
      "PPY",
      "PNE",
      "PVI",
      "PLS",
      "PGE",
      "PCF",
      "PLO",
      "BLR",
      "PLU"
    ),
    commune = c(
      "Wolfgang",
      "Buchs",
      "Münsterlingen",
      "Basel",
      "Zürich",
      "Luzern",
      "Bern",
      "Payerne",
      "Neuchâtel",
      "Visp",
      "Lausanne",
      "Genève",
      "La-Chaux-de-Fonds",
      "Locarno",
      "Balerna",
      "Lugano"
      )
  )


data_hirst <- dwhget_surface(param_short = species$tag,
                             year = c(2020),
                             iso_country_cd = "CH") %>% 
  mutate(datetime = ymd_hm(datetime)) %>% 
  mutate_if(is.character, ~as.factor(.)) %>% 
  inner_join(species, by = c("param_short" = "tag")) %>% 
  inner_join(stations, by = c("nat_abbr" = "tag"))

```

# Time Series Plots

```{r fig.height=9, fig.width=16}
stations_subset <- map(c(4, 8, 12, 16), ~stations %>% 
                         arrange(commune) %>% 
                         slice((.x - 3):.x) %>% 
                         pull(commune))

map(stations_subset, ~data_hirst %>% 
  filter(commune %in% .x) %>% 
  ggplot(aes(x = datetime, y = value, col = taxon)) +
    geom_line() +
    coord_cartesian(ylim = c(0, 5000)) +
    labs(y = expression(paste("Pollen Concentration [", m^-3, "]")),
       x = "") +
  scale_colour_discrete("") +
    facet_wrap(~commune))
```

```{r}

commune <- "Payerne" # Check stations tibble for all available locations
taxon <- "Betula" # Check species tibble for all available pollen taxa

data_hirst %>% 
  filter(taxon == taxon,
         commune == commune) %>% 
  ggplot(aes(x = datetime, y = value, col = taxon)) +
    geom_line() +
    ggtitle(paste("Hourly Pollen Concentrations in", commune)) +
  labs(y = expression(paste("Pollen Concentration [", m^-3, "]")),
       x = "") +
  scale_colour_discrete("")
```














































